### ISSUE TITLE
Project & Repo Rename Suggestion

### ISSUE THREAD

**Issue by davidsaulrodriguez** [davidsaulrodriguez/showcase#10]
As this is not completely a resume generator per-say, I suggest that this repo and the project itself be renamed. In a way, we are only showcasing a user's GitHub profile in a more appealing way than what GitHub offers. For this reason, I would suggest that this repo and the project itself be renamed to something like, **Showcaser** or more appropriately, **GitHub Profile Showcaser**.

I am not in marketing or great with creating project names, but I believe this is something that we can come up with before this project is on _December 17th 2020_.

Of course, after this project is presented we can continue to work on and evolve it to become a true resume generator as well. But as of right now, with the current state of the project I believe it should be renamed to something more appropriate and fitting towards its current functionality.

@Amarz94, @Mconway409, @dbridgman1 - Feel free to chime in on this, leaving your comments and remarks on this issue and let me know what you all think about this suggestion.

**Comment by Amarz94** [comment]
Approve

**Comment by davidsaulrodriguez** [comment]
After our Zoom meeting, it is safe to say this is an approved change to be made. But before this gets done I just want to make sure @Mconway409 is on board. We will reconvene during class today to discuss.

**Comment by davidsaulrodriguez** [comment]
**Showcase** it is!
